// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/wso2/asdlc/asdlc-service/clients/openchoreo"
)

// Ensure, that GitSecretClientMock does implement openchoreo.GitSecretClient.
// If this is not the case, regenerate this file with moq.
var _ openchoreo.GitSecretClient = &GitSecretClientMock{}

// GitSecretClientMock is a mock implementation of openchoreo.GitSecretClient.
//
//	func TestSomethingThatUsesGitSecretClient(t *testing.T) {
//
//		// make and configure a mocked openchoreo.GitSecretClient
//		mockedGitSecretClient := &GitSecretClientMock{
//			CreateGitSecretFunc: func(ctx context.Context, orgNS string, req openchoreo.CreateGitSecretRequest) (*openchoreo.GitSecretInfo, error) {
//				panic("mock out the CreateGitSecret method")
//			},
//			DeleteGitSecretFunc: func(ctx context.Context, orgNS string, name string) error {
//				panic("mock out the DeleteGitSecret method")
//			},
//			ListGitSecretsFunc: func(ctx context.Context, orgNS string) ([]*openchoreo.GitSecretInfo, error) {
//				panic("mock out the ListGitSecrets method")
//			},
//		}
//
//		// use mockedGitSecretClient in code that requires openchoreo.GitSecretClient
//		// and then make assertions.
//
//	}
type GitSecretClientMock struct {
	// CreateGitSecretFunc mocks the CreateGitSecret method.
	CreateGitSecretFunc func(ctx context.Context, orgNS string, req openchoreo.CreateGitSecretRequest) (*openchoreo.GitSecretInfo, error)

	// DeleteGitSecretFunc mocks the DeleteGitSecret method.
	DeleteGitSecretFunc func(ctx context.Context, orgNS string, name string) error

	// ListGitSecretsFunc mocks the ListGitSecrets method.
	ListGitSecretsFunc func(ctx context.Context, orgNS string) ([]*openchoreo.GitSecretInfo, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateGitSecret holds details about calls to the CreateGitSecret method.
		CreateGitSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgNS is the orgNS argument value.
			OrgNS string
			// Req is the req argument value.
			Req openchoreo.CreateGitSecretRequest
		}
		// DeleteGitSecret holds details about calls to the DeleteGitSecret method.
		DeleteGitSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgNS is the orgNS argument value.
			OrgNS string
			// Name is the name argument value.
			Name string
		}
		// ListGitSecrets holds details about calls to the ListGitSecrets method.
		ListGitSecrets []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgNS is the orgNS argument value.
			OrgNS string
		}
	}
	lockCreateGitSecret sync.RWMutex
	lockDeleteGitSecret sync.RWMutex
	lockListGitSecrets  sync.RWMutex
}

// CreateGitSecret calls CreateGitSecretFunc.
func (mock *GitSecretClientMock) CreateGitSecret(ctx context.Context, orgNS string, req openchoreo.CreateGitSecretRequest) (*openchoreo.GitSecretInfo, error) {
	if mock.CreateGitSecretFunc == nil {
		panic("GitSecretClientMock.CreateGitSecretFunc: method is nil but GitSecretClient.CreateGitSecret was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OrgNS string
		Req   openchoreo.CreateGitSecretRequest
	}{
		Ctx:   ctx,
		OrgNS: orgNS,
		Req:   req,
	}
	mock.lockCreateGitSecret.Lock()
	mock.calls.CreateGitSecret = append(mock.calls.CreateGitSecret, callInfo)
	mock.lockCreateGitSecret.Unlock()
	return mock.CreateGitSecretFunc(ctx, orgNS, req)
}

// CreateGitSecretCalls gets all the calls that were made to CreateGitSecret.
// Check the length with:
//
//	len(mockedGitSecretClient.CreateGitSecretCalls())
func (mock *GitSecretClientMock) CreateGitSecretCalls() []struct {
	Ctx   context.Context
	OrgNS string
	Req   openchoreo.CreateGitSecretRequest
} {
	var calls []struct {
		Ctx   context.Context
		OrgNS string
		Req   openchoreo.CreateGitSecretRequest
	}
	mock.lockCreateGitSecret.RLock()
	calls = mock.calls.CreateGitSecret
	mock.lockCreateGitSecret.RUnlock()
	return calls
}

// DeleteGitSecret calls DeleteGitSecretFunc.
func (mock *GitSecretClientMock) DeleteGitSecret(ctx context.Context, orgNS string, name string) error {
	if mock.DeleteGitSecretFunc == nil {
		panic("GitSecretClientMock.DeleteGitSecretFunc: method is nil but GitSecretClient.DeleteGitSecret was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OrgNS string
		Name  string
	}{
		Ctx:   ctx,
		OrgNS: orgNS,
		Name:  name,
	}
	mock.lockDeleteGitSecret.Lock()
	mock.calls.DeleteGitSecret = append(mock.calls.DeleteGitSecret, callInfo)
	mock.lockDeleteGitSecret.Unlock()
	return mock.DeleteGitSecretFunc(ctx, orgNS, name)
}

// DeleteGitSecretCalls gets all the calls that were made to DeleteGitSecret.
// Check the length with:
//
//	len(mockedGitSecretClient.DeleteGitSecretCalls())
func (mock *GitSecretClientMock) DeleteGitSecretCalls() []struct {
	Ctx   context.Context
	OrgNS string
	Name  string
} {
	var calls []struct {
		Ctx   context.Context
		OrgNS string
		Name  string
	}
	mock.lockDeleteGitSecret.RLock()
	calls = mock.calls.DeleteGitSecret
	mock.lockDeleteGitSecret.RUnlock()
	return calls
}

// ListGitSecrets calls ListGitSecretsFunc.
func (mock *GitSecretClientMock) ListGitSecrets(ctx context.Context, orgNS string) ([]*openchoreo.GitSecretInfo, error) {
	if mock.ListGitSecretsFunc == nil {
		panic("GitSecretClientMock.ListGitSecretsFunc: method is nil but GitSecretClient.ListGitSecrets was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OrgNS string
	}{
		Ctx:   ctx,
		OrgNS: orgNS,
	}
	mock.lockListGitSecrets.Lock()
	mock.calls.ListGitSecrets = append(mock.calls.ListGitSecrets, callInfo)
	mock.lockListGitSecrets.Unlock()
	return mock.ListGitSecretsFunc(ctx, orgNS)
}

// ListGitSecretsCalls gets all the calls that were made to ListGitSecrets.
// Check the length with:
//
//	len(mockedGitSecretClient.ListGitSecretsCalls())
func (mock *GitSecretClientMock) ListGitSecretsCalls() []struct {
	Ctx   context.Context
	OrgNS string
} {
	var calls []struct {
		Ctx   context.Context
		OrgNS string
	}
	mock.lockListGitSecrets.RLock()
	calls = mock.calls.ListGitSecrets
	mock.lockListGitSecrets.RUnlock()
	return calls
}
