// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/wso2/asdlc/asdlc-service/clients/openchoreo"
)

// Ensure, that SecretRefClientMock does implement openchoreo.SecretRefClient.
// If this is not the case, regenerate this file with moq.
var _ openchoreo.SecretRefClient = &SecretRefClientMock{}

// SecretRefClientMock is a mock implementation of openchoreo.SecretRefClient.
//
//	func TestSomethingThatUsesSecretRefClient(t *testing.T) {
//
//		// make and configure a mocked openchoreo.SecretRefClient
//		mockedSecretRefClient := &SecretRefClientMock{
//			EnsureSecretReferenceFunc: func(ctx context.Context, namespace string, name string, vaultPath string) error {
//				panic("mock out the EnsureSecretReference method")
//			},
//		}
//
//		// use mockedSecretRefClient in code that requires openchoreo.SecretRefClient
//		// and then make assertions.
//
//	}
type SecretRefClientMock struct {
	// EnsureSecretReferenceFunc mocks the EnsureSecretReference method.
	EnsureSecretReferenceFunc func(ctx context.Context, namespace string, name string, vaultPath string) error

	// calls tracks calls to the methods.
	calls struct {
		// EnsureSecretReference holds details about calls to the EnsureSecretReference method.
		EnsureSecretReference []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
			// VaultPath is the vaultPath argument value.
			VaultPath string
		}
	}
	lockEnsureSecretReference sync.RWMutex
}

// EnsureSecretReference calls EnsureSecretReferenceFunc.
func (mock *SecretRefClientMock) EnsureSecretReference(ctx context.Context, namespace string, name string, vaultPath string) error {
	if mock.EnsureSecretReferenceFunc == nil {
		panic("SecretRefClientMock.EnsureSecretReferenceFunc: method is nil but SecretRefClient.EnsureSecretReference was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
		Name      string
		VaultPath string
	}{
		Ctx:       ctx,
		Namespace: namespace,
		Name:      name,
		VaultPath: vaultPath,
	}
	mock.lockEnsureSecretReference.Lock()
	mock.calls.EnsureSecretReference = append(mock.calls.EnsureSecretReference, callInfo)
	mock.lockEnsureSecretReference.Unlock()
	return mock.EnsureSecretReferenceFunc(ctx, namespace, name, vaultPath)
}

// EnsureSecretReferenceCalls gets all the calls that were made to EnsureSecretReference.
// Check the length with:
//
//	len(mockedSecretRefClient.EnsureSecretReferenceCalls())
func (mock *SecretRefClientMock) EnsureSecretReferenceCalls() []struct {
	Ctx       context.Context
	Namespace string
	Name      string
	VaultPath string
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
		Name      string
		VaultPath string
	}
	mock.lockEnsureSecretReference.RLock()
	calls = mock.calls.EnsureSecretReference
	mock.lockEnsureSecretReference.RUnlock()
	return calls
}
