// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/wso2/asdlc/asdlc-service/clients/openchoreo"
	"github.com/wso2/asdlc/asdlc-service/clients/secretmanagersvc"
)

// Ensure, that SecretReferenceClientMock does implement openchoreo.SecretReferenceClient.
// If this is not the case, regenerate this file with moq.
var _ openchoreo.SecretReferenceClient = &SecretReferenceClientMock{}

// SecretReferenceClientMock is a mock implementation of openchoreo.SecretReferenceClient.
//
//	func TestSomethingThatUsesSecretReferenceClient(t *testing.T) {
//
//		// make and configure a mocked openchoreo.SecretReferenceClient
//		mockedSecretReferenceClient := &SecretReferenceClientMock{
//			CreateSecretReferenceFunc: func(ctx context.Context, orgNS string, req secretmanagersvc.CreateSecretReferenceRequest) (*secretmanagersvc.SecretReference, error) {
//				panic("mock out the CreateSecretReference method")
//			},
//			DeleteSecretReferenceFunc: func(ctx context.Context, orgNS string, name string) error {
//				panic("mock out the DeleteSecretReference method")
//			},
//			GetSecretReferenceFunc: func(ctx context.Context, orgNS string, name string) (*secretmanagersvc.SecretReference, error) {
//				panic("mock out the GetSecretReference method")
//			},
//			ListSecretReferencesFunc: func(ctx context.Context, orgNS string, componentName string) ([]*secretmanagersvc.SecretReference, error) {
//				panic("mock out the ListSecretReferences method")
//			},
//			UpdateSecretReferenceFunc: func(ctx context.Context, orgNS string, name string, req secretmanagersvc.CreateSecretReferenceRequest) (*secretmanagersvc.SecretReference, error) {
//				panic("mock out the UpdateSecretReference method")
//			},
//		}
//
//		// use mockedSecretReferenceClient in code that requires openchoreo.SecretReferenceClient
//		// and then make assertions.
//
//	}
type SecretReferenceClientMock struct {
	// CreateSecretReferenceFunc mocks the CreateSecretReference method.
	CreateSecretReferenceFunc func(ctx context.Context, orgNS string, req secretmanagersvc.CreateSecretReferenceRequest) (*secretmanagersvc.SecretReference, error)

	// DeleteSecretReferenceFunc mocks the DeleteSecretReference method.
	DeleteSecretReferenceFunc func(ctx context.Context, orgNS string, name string) error

	// GetSecretReferenceFunc mocks the GetSecretReference method.
	GetSecretReferenceFunc func(ctx context.Context, orgNS string, name string) (*secretmanagersvc.SecretReference, error)

	// ListSecretReferencesFunc mocks the ListSecretReferences method.
	ListSecretReferencesFunc func(ctx context.Context, orgNS string, componentName string) ([]*secretmanagersvc.SecretReference, error)

	// UpdateSecretReferenceFunc mocks the UpdateSecretReference method.
	UpdateSecretReferenceFunc func(ctx context.Context, orgNS string, name string, req secretmanagersvc.CreateSecretReferenceRequest) (*secretmanagersvc.SecretReference, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateSecretReference holds details about calls to the CreateSecretReference method.
		CreateSecretReference []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgNS is the orgNS argument value.
			OrgNS string
			// Req is the req argument value.
			Req secretmanagersvc.CreateSecretReferenceRequest
		}
		// DeleteSecretReference holds details about calls to the DeleteSecretReference method.
		DeleteSecretReference []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgNS is the orgNS argument value.
			OrgNS string
			// Name is the name argument value.
			Name string
		}
		// GetSecretReference holds details about calls to the GetSecretReference method.
		GetSecretReference []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgNS is the orgNS argument value.
			OrgNS string
			// Name is the name argument value.
			Name string
		}
		// ListSecretReferences holds details about calls to the ListSecretReferences method.
		ListSecretReferences []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgNS is the orgNS argument value.
			OrgNS string
			// ComponentName is the componentName argument value.
			ComponentName string
		}
		// UpdateSecretReference holds details about calls to the UpdateSecretReference method.
		UpdateSecretReference []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgNS is the orgNS argument value.
			OrgNS string
			// Name is the name argument value.
			Name string
			// Req is the req argument value.
			Req secretmanagersvc.CreateSecretReferenceRequest
		}
	}
	lockCreateSecretReference sync.RWMutex
	lockDeleteSecretReference sync.RWMutex
	lockGetSecretReference    sync.RWMutex
	lockListSecretReferences  sync.RWMutex
	lockUpdateSecretReference sync.RWMutex
}

// CreateSecretReference calls CreateSecretReferenceFunc.
func (mock *SecretReferenceClientMock) CreateSecretReference(ctx context.Context, orgNS string, req secretmanagersvc.CreateSecretReferenceRequest) (*secretmanagersvc.SecretReference, error) {
	if mock.CreateSecretReferenceFunc == nil {
		panic("SecretReferenceClientMock.CreateSecretReferenceFunc: method is nil but SecretReferenceClient.CreateSecretReference was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OrgNS string
		Req   secretmanagersvc.CreateSecretReferenceRequest
	}{
		Ctx:   ctx,
		OrgNS: orgNS,
		Req:   req,
	}
	mock.lockCreateSecretReference.Lock()
	mock.calls.CreateSecretReference = append(mock.calls.CreateSecretReference, callInfo)
	mock.lockCreateSecretReference.Unlock()
	return mock.CreateSecretReferenceFunc(ctx, orgNS, req)
}

// CreateSecretReferenceCalls gets all the calls that were made to CreateSecretReference.
// Check the length with:
//
//	len(mockedSecretReferenceClient.CreateSecretReferenceCalls())
func (mock *SecretReferenceClientMock) CreateSecretReferenceCalls() []struct {
	Ctx   context.Context
	OrgNS string
	Req   secretmanagersvc.CreateSecretReferenceRequest
} {
	var calls []struct {
		Ctx   context.Context
		OrgNS string
		Req   secretmanagersvc.CreateSecretReferenceRequest
	}
	mock.lockCreateSecretReference.RLock()
	calls = mock.calls.CreateSecretReference
	mock.lockCreateSecretReference.RUnlock()
	return calls
}

// DeleteSecretReference calls DeleteSecretReferenceFunc.
func (mock *SecretReferenceClientMock) DeleteSecretReference(ctx context.Context, orgNS string, name string) error {
	if mock.DeleteSecretReferenceFunc == nil {
		panic("SecretReferenceClientMock.DeleteSecretReferenceFunc: method is nil but SecretReferenceClient.DeleteSecretReference was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OrgNS string
		Name  string
	}{
		Ctx:   ctx,
		OrgNS: orgNS,
		Name:  name,
	}
	mock.lockDeleteSecretReference.Lock()
	mock.calls.DeleteSecretReference = append(mock.calls.DeleteSecretReference, callInfo)
	mock.lockDeleteSecretReference.Unlock()
	return mock.DeleteSecretReferenceFunc(ctx, orgNS, name)
}

// DeleteSecretReferenceCalls gets all the calls that were made to DeleteSecretReference.
// Check the length with:
//
//	len(mockedSecretReferenceClient.DeleteSecretReferenceCalls())
func (mock *SecretReferenceClientMock) DeleteSecretReferenceCalls() []struct {
	Ctx   context.Context
	OrgNS string
	Name  string
} {
	var calls []struct {
		Ctx   context.Context
		OrgNS string
		Name  string
	}
	mock.lockDeleteSecretReference.RLock()
	calls = mock.calls.DeleteSecretReference
	mock.lockDeleteSecretReference.RUnlock()
	return calls
}

// GetSecretReference calls GetSecretReferenceFunc.
func (mock *SecretReferenceClientMock) GetSecretReference(ctx context.Context, orgNS string, name string) (*secretmanagersvc.SecretReference, error) {
	if mock.GetSecretReferenceFunc == nil {
		panic("SecretReferenceClientMock.GetSecretReferenceFunc: method is nil but SecretReferenceClient.GetSecretReference was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OrgNS string
		Name  string
	}{
		Ctx:   ctx,
		OrgNS: orgNS,
		Name:  name,
	}
	mock.lockGetSecretReference.Lock()
	mock.calls.GetSecretReference = append(mock.calls.GetSecretReference, callInfo)
	mock.lockGetSecretReference.Unlock()
	return mock.GetSecretReferenceFunc(ctx, orgNS, name)
}

// GetSecretReferenceCalls gets all the calls that were made to GetSecretReference.
// Check the length with:
//
//	len(mockedSecretReferenceClient.GetSecretReferenceCalls())
func (mock *SecretReferenceClientMock) GetSecretReferenceCalls() []struct {
	Ctx   context.Context
	OrgNS string
	Name  string
} {
	var calls []struct {
		Ctx   context.Context
		OrgNS string
		Name  string
	}
	mock.lockGetSecretReference.RLock()
	calls = mock.calls.GetSecretReference
	mock.lockGetSecretReference.RUnlock()
	return calls
}

// ListSecretReferences calls ListSecretReferencesFunc.
func (mock *SecretReferenceClientMock) ListSecretReferences(ctx context.Context, orgNS string, componentName string) ([]*secretmanagersvc.SecretReference, error) {
	if mock.ListSecretReferencesFunc == nil {
		panic("SecretReferenceClientMock.ListSecretReferencesFunc: method is nil but SecretReferenceClient.ListSecretReferences was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgNS         string
		ComponentName string
	}{
		Ctx:           ctx,
		OrgNS:         orgNS,
		ComponentName: componentName,
	}
	mock.lockListSecretReferences.Lock()
	mock.calls.ListSecretReferences = append(mock.calls.ListSecretReferences, callInfo)
	mock.lockListSecretReferences.Unlock()
	return mock.ListSecretReferencesFunc(ctx, orgNS, componentName)
}

// ListSecretReferencesCalls gets all the calls that were made to ListSecretReferences.
// Check the length with:
//
//	len(mockedSecretReferenceClient.ListSecretReferencesCalls())
func (mock *SecretReferenceClientMock) ListSecretReferencesCalls() []struct {
	Ctx           context.Context
	OrgNS         string
	ComponentName string
} {
	var calls []struct {
		Ctx           context.Context
		OrgNS         string
		ComponentName string
	}
	mock.lockListSecretReferences.RLock()
	calls = mock.calls.ListSecretReferences
	mock.lockListSecretReferences.RUnlock()
	return calls
}

// UpdateSecretReference calls UpdateSecretReferenceFunc.
func (mock *SecretReferenceClientMock) UpdateSecretReference(ctx context.Context, orgNS string, name string, req secretmanagersvc.CreateSecretReferenceRequest) (*secretmanagersvc.SecretReference, error) {
	if mock.UpdateSecretReferenceFunc == nil {
		panic("SecretReferenceClientMock.UpdateSecretReferenceFunc: method is nil but SecretReferenceClient.UpdateSecretReference was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OrgNS string
		Name  string
		Req   secretmanagersvc.CreateSecretReferenceRequest
	}{
		Ctx:   ctx,
		OrgNS: orgNS,
		Name:  name,
		Req:   req,
	}
	mock.lockUpdateSecretReference.Lock()
	mock.calls.UpdateSecretReference = append(mock.calls.UpdateSecretReference, callInfo)
	mock.lockUpdateSecretReference.Unlock()
	return mock.UpdateSecretReferenceFunc(ctx, orgNS, name, req)
}

// UpdateSecretReferenceCalls gets all the calls that were made to UpdateSecretReference.
// Check the length with:
//
//	len(mockedSecretReferenceClient.UpdateSecretReferenceCalls())
func (mock *SecretReferenceClientMock) UpdateSecretReferenceCalls() []struct {
	Ctx   context.Context
	OrgNS string
	Name  string
	Req   secretmanagersvc.CreateSecretReferenceRequest
} {
	var calls []struct {
		Ctx   context.Context
		OrgNS string
		Name  string
		Req   secretmanagersvc.CreateSecretReferenceRequest
	}
	mock.lockUpdateSecretReference.RLock()
	calls = mock.calls.UpdateSecretReference
	mock.lockUpdateSecretReference.RUnlock()
	return calls
}
