package openchoreo

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"slices"

	"github.com/wso2/asdlc/asdlc-service/clients/httpx"
	"github.com/wso2/asdlc/asdlc-service/clients/openchoreo/gen"
	"github.com/wso2/asdlc/asdlc-service/clients/requests"
)

// AuthProvider is the auth-token contract the OC client depends on. Lets us
// swap `*oauth.TokenProvider` (the only production impl) for a fake in
// tests without touching the oauth package. Method signatures intentionally
// match `*oauth.TokenProvider` so it satisfies the interface as-is.
type AuthProvider interface {
	Token() (string, error)
	Invalidate()
}

// Config drives the OpenChoreo client construction.
type Config struct {
	BaseURL      string
	HostHeader   string
	AuthProvider AuthProvider
	RetryConfig  requests.RequestRetryConfig
}

// newGenClient builds a *gen.ClientWithResponses with the three-layer
// transport stack:
//
//	1. httpx.WrapTransport (innermost) — stamps X-Correlation-ID for tracing
//	2. RetryableHTTPClient (middle) — jittered exponential backoff on
//	   transient codes; 401 invalidates the cached service token and retries
//	3. RequestEditorFn (outermost, oapi-codegen hook) — sets Authorization,
//	   Host, and X-Use-OpenAPI on every request
//
// Auth lives in the editor (not a RoundTripper) so the retry middleware sees
// a fresh token after invalidation: the editor runs on every attempt and
// re-calls AuthProvider.Token(), which returns the newly-fetched token after
// the 401 callback called Invalidate().
func newGenClient(cfg Config) (*gen.ClientWithResponses, error) {
	if cfg.BaseURL == "" {
		return nil, errors.New("openchoreo: Config.BaseURL is required")
	}

	retryCfg := cfg.RetryConfig
	if retryCfg.RetryOnStatus == nil {
		// Default OC policy: invalidate token on 401, retry; otherwise fall
		// back to the transient-error set. We intentionally don't expose this
		// as the package default — passing it via Config keeps the rule next
		// to its only valid caller (AuthProvider.Invalidate).
		retryCfg.RetryOnStatus = func(status int) bool {
			if status == http.StatusUnauthorized {
				if cfg.AuthProvider != nil {
					slog.Info("openchoreo: 401, invalidating cached token and retrying")
					cfg.AuthProvider.Invalidate()
				}
				return true
			}
			return slices.Contains(requests.TransientHTTPErrorCodes, status)
		}
	}

	inner := &http.Client{Transport: httpx.WrapTransport(nil)}
	outer := requests.NewRetryableHTTPClient(inner, retryCfg)

	authEditor := func(ctx context.Context, req *http.Request) error {
		if cfg.HostHeader != "" {
			req.Host = cfg.HostHeader
		}
		req.Header.Set("X-Use-OpenAPI", "true")
		tok, err := authToken(ctx, cfg.AuthProvider)
		if err != nil {
			return err
		}
		if tok != "" {
			req.Header.Set("Authorization", "Bearer "+tok)
		}
		return nil
	}

	c, err := gen.NewClientWithResponses(
		cfg.BaseURL,
		gen.WithHTTPClient(outer),
		gen.WithRequestEditorFn(authEditor),
	)
	if err != nil {
		return nil, fmt.Errorf("openchoreo: build gen client: %w", err)
	}
	return c, nil
}

// authToken returns the M2M service token used to authenticate against the
// OpenChoreo REST API. The BFF acts as a platform orchestrator: it identifies
// itself by a single service-credentials subject that holds a
// ClusterAuthzRoleBinding on the OC control plane (see
// `wso2cloud-deployement-main/dataplane/.../layer-2/openchoreo/controlplane.yaml`,
// binding name `app-factory-bff-binding`). The target namespace is supplied
// explicitly in the request URL path — OC honors it, unlike platform-api
// which derived NS from the JWT's `ouId` claim and routed BFF calls to the
// Admin tenant. See `docs/superpowers/plans/2026-05-29-bff-oc-rest-direct.md`.
//
// Returns `("", nil)` when no provider is configured (local k3d — OC accepts
// unauthenticated calls in the OSS default; caller emits the request without
// an Authorization header). Returns a non-nil error when the provider is
// configured but cannot mint a token — the request is then aborted by the
// editor instead of being sent unauthenticated, so callers see the actual
// auth failure rather than a downstream 401 generated by `RetryableHTTPClient`
// resending the same request without re-running the editor.
func authToken(_ context.Context, ap AuthProvider) (string, error) {
	if ap == nil {
		return "", nil
	}
	tok, err := ap.Token()
	if err != nil {
		return "", fmt.Errorf("openchoreo: service token fetch failed: %w", err)
	}
	return tok, nil
}
